# docker-compose.yml for scienceos-2api

services:
  # 前台总机服务 (Nginx)
  nginx:
    image: nginx:latest
    ports:
      # 将主机的 ${LISTEN_PORT} 端口映射到 Nginx 的 80 端口
      - "${LISTEN_PORT:-8082}:80"
    volumes:
      # 挂载 Nginx 配置文件
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - scienceos-api
    networks:
      - shared_network
    restart: unless-stopped

  # 后端核心应用服务 (FastAPI)
  scienceos-api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    # 从 .env 文件加载环境变量
    env_file:
      - .env
    # 允许容器内应用访问宿主机的网络 (用于代理)
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - shared_network
    # 不直接对外暴露端口，由 Nginx 统一代理

networks:
  shared_network:
    driver: bridge
